# FROM python:3.12-slim as base

# WORKDIR /usr/src/app

# RUN apt-get update && apt-get install -y --no-install-recommends \
#     freeglut3-dev \
#     build-essential \
#     libglib2.0-0 \
#     xvfb \
#     x11-apps \
#     libxext6 \
#     libxtst6 \
#     libxrender1 \
#     x11-xserver-utils \
#     && rm -rf /var/lib/apt/lists/*

# FROM base as builder

# COPY requirements.txt ./

# # Install Python dependencies
# RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# # Final stage for the production image
# FROM base

# # Copy installed Python packages from builder stage
# COPY --from=builder /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages

# # Copy the local directory contents into the container at /usr/src/app
# COPY . .

# # Ensure scripts are executable
# RUN chmod +x virtual_display.sh entrypoint.sh

# EXPOSE 5001

# # Command to run the entrypoint script
# CMD ["./entrypoint.sh"]


# Use the official Python image as the base
FROM python:3.11.3-slim as base

WORKDIR /usr/src/app

# Install system dependencies required for a virtual display and other operations
RUN apt-get update && apt-get install -y --no-install-recommends \
    freeglut3-dev \
    build-essential \
    libglib2.0-0 \
    xvfb \
    x11-apps \
    libxext6 \
    libxtst6 \
    libxrender1 \
    x11-xserver-utils \
    && rm -rf /var/lib/apt/lists/*

# Builder stage to install Python dependencies in a virtual environment
FROM base as builder

COPY requirements.txt ./

# Create a virtual environment in the /venv directory
RUN python -m venv /venv

# Ensure that we use the virtual environment’s Python and pip for subsequent commands
ENV PATH="/venv/bin:$PATH"

# Upgrade pip and install the Python dependencies in the virtual environment
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# Final stage for the production image
FROM base

# Copy the virtual environment from the builder stage
COPY --from=builder /venv /venv

# Set environment variables to ensure we use the virtual environment’s runtime
ENV PATH="/venv/bin:$PATH"

# Copy the local directory contents into the container at /usr/src/app
COPY . .

# Ensure scripts are executable
RUN chmod +x virtual_display.sh entrypoint.sh

EXPOSE 5001

# Command to run the entrypoint script
CMD ["./entrypoint.sh"]
