FROM python:3.11-slim as base

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y --no-install-recommends \
    freeglut3-dev \
    build-essential \
    libglib2.0-0 \
    xvfb \
    x11-apps \
    libxext6 \
    libxtst6 \
    libxrender1 \
    x11-xserver-utils \
    && rm -rf /var/lib/apt/lists/*

FROM base as builder

COPY requirements.txt ./

# Install Python dependencies
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# Final stage for the production image
FROM base

# Copy installed Python packages from builder stage
COPY --from=builder /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages

# Copy the local directory contents into the container at /usr/src/app
COPY . .

# Ensure scripts are executable
RUN chmod +x virtual_display.sh entrypoint.sh

EXPOSE 5000

# Command to run the entrypoint script
CMD ["./entrypoint.sh"]