# # Use Ubuntu as the parent image
# FROM ubuntu:latest

# # Set noninteractive installation mode
# ENV DEBIAN_FRONTEND=noninteractive
# ENV TZ=UTC


# # Set the working directory in the container
# WORKDIR /usr/src/app

# # Install Python, OpenCV dependencies, and other essential tools
# RUN apt-get update && apt-get install -y \
#     python3 \
#     python3-pip \
#     libopencv-dev \
#     python3-opencv \
#     libgl1-mesa-dev \
#     libglu1-mesa-dev \
#     freeglut3-dev \
#     x11-apps \
#     libxext6 \
#     libxtst6 \
#     libxrender1 \
#     build-essential \
#     xvfb \
#     x11-xserver-utils \
#     bash


# # Copy the local directory contents into the container at /usr/src/app
# COPY . .


# #set permission
# RUN chmod +x start.sh
# RUN ./start.sh

# # Install any needed packages specified in requirements.txt
# RUN pip3 install --upgrade pip && pip3 install -r requirements.txt

# RUN chmod +x virtual_display.sh
# RUN bash ./virtual_display.sh

# # Command to run the application
# CMD ["python3", "main.py"]

# Use Ubuntu as the parent image
FROM ubuntu:latest

# Set noninteractive installation mode
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=UTC

# Set the working directory in the container
WORKDIR /usr/src/app

# Install Python, OpenCV dependencies, and other essential tools
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    libopencv-dev \
    python3-opencv \
    libgl1-mesa-dev \
    libglu1-mesa-dev \
    freeglut3-dev \
    x11-apps \
    libxext6 \
    libxtst6 \
    libxrender1 \
    build-essential \
    xvfb \
    python3-gpiozero \
    python3-pigpio \
    x11-xserver-utils \
    bash && \
    rm -rf /var/lib/apt/lists/*

# Copy the local directory contents into the container at /usr/src/app
COPY . .

# Install any needed packages specified in requirements.txt
RUN pip3 install --upgrade pip && pip3 install -r requirements.txt

# Set permission and create an entrypoint script
RUN chmod +x virtual_display.sh

RUN chmod +x entrypoint.sh

# Command to run the entrypoint script
CMD ["./entrypoint.sh"]