version: '3'

services:
  mjpgstreamer:
    build:
      context: ./camera_stream
      dockerfile: Dockerfile
    ports:
      - '8500:8080'
    volumes:
      - mydata:/usr/www
    devices:
      - '/dev/video0:/dev/video0'
    networks:
      - mynetwork

  mazecnn:
    build:
      context: .
      dockerfile: Dockerfile
    environment :
      - DISPLAY=:99
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./:/usr/src/app
    ports:
      - '5000:5000'
    networks:
      - mynetwork
volumes:
  mydata:

networks:
  mynetwork:
