# # Use Ubuntu as the parent image
# FROM ubuntu:latest

# # Set noninteractive installation mode
# ENV DEBIAN_FRONTEND=noninteractive
# ENV TZ=UTC

# # Set the working directory in the container
# WORKDIR /usr/src/app

# # Install Python, OpenCV dependencies, and other essential tools
# RUN apt-get update && apt-get install -y \
#     python3 \
#     python3-pip \
#     libopencv-dev \
#     python3-opencv \
#     libgl1-mesa-dev \
#     libglu1-mesa-dev \
#     freeglut3-dev \
#     x11-apps \
#     libxext6 \
#     libxtst6 \
#     libxrender1 \
#     build-essential \
#     xvfb \
#     python3-gpiozero \
#     python3-pigpio \
#     x11-xserver-utils \
#     bash && \
#     rm -rf /var/lib/apt/lists/*

# # Copy the local directory contents into the container at /usr/src/app
# COPY . .

# # Install any needed packages specified in requirements.txt
# RUN pip3 install --upgrade pip && pip3 install -r requirements.txt

# # Set permission and create an entrypoint script
# RUN chmod +x virtual_display.sh

# RUN chmod +x entrypoint.sh

# # Command to run the entrypoint script
# CMD ["entrypoint.sh"]

# Build stage
FROM ubuntu:latest as builder

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=UTC

WORKDIR /usr/src/app

# Install build dependencies
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    libopencv-dev \
    python3-opencv \
    libgl1-mesa-dev \
    libglu1-mesa-dev \
    freeglut3-dev \
    x11-apps \
    libxext6 \
    libxtst6 \
    libxrender1 \
    build-essential \
    xvfb \
    x11-xserver-utils \
    bash && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copy only the requirements.txt initially to leverage Docker cache
COPY requirements.txt ./

# Install Python dependencies
RUN pip3 install --upgrade pip && pip3 install -r requirements.txt

# Copy the rest of the application code
COPY . .

# Runtime stage
FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=UTC

WORKDIR /usr/src/app

# Install runtime dependencies
RUN apt-get update && apt-get install -y \
    python3 \
    libopencv-dev \
    python3-opencv \
    libgl1-mesa-dev \
    libxrender1 \
    xvfb \
    x11-xserver-utils \
    bash && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copy built artifacts from the builder stage
COPY --from=builder /usr/src/app /usr/src/app

# Set permission for entrypoint and virtual display scripts
RUN chmod +x entrypoint.sh virtual_display.sh

# Command to run the entrypoint script
CMD ["entrypoint.sh"]