# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Install OpenCV dependencies
RUN apt-get update && apt-get install -y \
    libopencv-dev \
    python3-opencv \ 
    python3-gpiozero \
    python3-pigpio

COPY . .

EXPOSE 5500

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "app.py"]
