version: '3'

services:
  mjpg-streamer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8500:8080'
    volumes:
      - mydata:/usr/www # Named volume
    # Or for bind mount:
    # - ./localfolder:/usr/www
    command:
      [
        'dumb-init',
        '--',
        'mjpg_streamer',
        '-i',
        'input_uvc.so',
        '-o',
        'output_http.so -w /usr/www -p 8080',
      ]

volumes:
  mydata:
